
ACCESS-TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqb2huMjM0NDRAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM0NDU1OTMsImV4cCI6MTc2MzQ0NzM5M30.2Sve7iyT7FYmzHz_4aDfXrIiBL9jMg-VUA37jNEy1c8


###hellox
GET http://localhost:3000/app/hi;

### hi
POST http://localhost:3000/api/v1/users


###signup
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
  "name": "John peter Doe",
  "email": "john@example.com",
  "password": "securepassword123"
}

###signin
POST http://localhost:3000/api/users/signin
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "securepassword123"

}
###find all
GET http://localhost:3000/api/users/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqb2huMjM0NDRAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjQwMTIwNzIsImV4cCI6MTc2NDAxOTI3Mn0.M71kxTHjclTFjCUTzCk8K5wDKMVpIaTjyDH3ZtKfcF8





###find one
GET http://localhost:3000/api/users/single/23

Content-Type: application/json




###get profile
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqb2huMjM0NDRAZXhhbXBsZS5jb20iLCJpYXQiOjE3NjM5NjU4NjYsImV4cCI6MTc2Mzk3MzA2Nn0.XpIlwNvmkYZZJUN1cB8ltyIv3ZC2kkopYrIquMVbC2A


Content-Type: application/json